services:

  db:
    image: postgres
    restart: always
    ports:
      - 8083:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080